version: '3'
services:
  redis:
    image: redis:alpine3.18
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql1
    hostname: sql1
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Jadco0812@
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - ./mysql:/var/opt/mssql/data
volumes:
  redis-data:
    driver: ./redis